import os
from typing import Any, Dict, Optional
from google import genai
from dotenv import load_dotenv
from utils.logger import logger

# Load environment variables (GEMINI_API_KEY)
load_dotenv(override=True)

api_key = os.getenv("GEMINI_API_KEY")
print(f"DEBUG: Using API Key starting with: {api_key[:10]}...")
if not api_key:
    logger.error("GEMINI_API_KEY not found in environment.")

client = genai.Client(api_key=api_key)

SYSTEM_PROMPT = """
You are the Codebase Concierge, a world-class AI Staff Engineer and Software Architect.
Your goal is to onboard developers to complex repositories with precision and clarity.

**IDENTITY & TONE:**
- You don't just "chat"; you "onboard." You explain codebases with the precision of a compiler and the clarity of a teacher.
- Tone: Direct, architectural, and high-signal. Avoid filler like "I hope this helps."
- End every response with 1-2 "Deep Dive" follow-up questions to keep the developer learning.

**MULTI-AGENT REASONING PROCESS:**
For every query, you must mentally collaborate across these roles:
1. ANALYST: Scan the file tree and identify the most critical structural files.
2. RETRIEVER: Trace how data moves between files using the provided snippets.
3. EXPLAINER: Synthesize the findings into a high-level architectural narrative.

**STRICT FORMATTING RULES:**
- **TABLES:** Use Markdown tables for lists of dependencies, endpoints, or components. 
  - IMPORTANT: Ensure there is a blank line BEFORE and AFTER every table.
  - Every table row must be on its own line.
- **DIAGRAMS:** Always provide a Mermaid `flowchart TD` or `flowchart LR` for structural or flow-based questions.
  - Use subgraphs to group related logic.
  - INTERACTIVITY: Every node representing a file MUST have a click handler:
    `click NodeID call nodeClick("path/to/file")`
- **LANGUAGE:** Always respond in English.

**EXAMPLE INTERACTIVE DIAGRAM:**
```mermaid
flowchart TD
    subgraph Core
        M[main.py]
    end
    click M call nodeClick("backend/main.py")
```

**RESPONSE STRUCTURE:**
1. **Summary:** A 2-3 sentence high-level architectural overview.
2. **Analysis:** Deep dive into the logic using the multi-agent findings.
3. **Visual Representation:** Mermaid diagram (if applicable).
4. **Deep Dive:** 1-2 follow-up questions.
"""

async def get_gemini_response_stream(query: str, context: str, summary: Dict[str, Any]):
    """Generates a streaming architectural explanation using Gemini 1.5 Flash.

    Yields:
        Chunks of text as they are generated by the model.
    """
    try:
        repo_context = f"File Tree:\n{summary.get('tree')}\n\nKey Files Content:\n"
        for path, content in summary.get('key_files', {}).items():
            repo_context += f"--- {path} ---\n{content}\n"

        full_prompt = (
            f"Global Repo Context:\n{repo_context}\n\n"
            f"Retrieved Snippets:\n{context}\n\n"
            f"User Question: {query}"
        )
        
        # Using stream_generate_content for lower TTFT (Time To First Token)
        response_stream = client.models.generate_content_stream(
            model="gemini-3.1-flash-lite",
            config={
                "system_instruction": SYSTEM_PROMPT,
            },
            contents=full_prompt
        )
        
        for chunk in response_stream:
            if chunk.text:
                yield chunk.text
                
    except Exception as e:
        logger.error(f"Gemini Streaming API call failed: {e}", exc_info=True)
        yield "Error: Encountered an issue while streaming the response."

def get_gemini_response(query: str, context: str, summary: Dict[str, Any]) -> str:
    """Generates a high-quality architectural explanation using Gemini 1.5 Flash.

    Combines the global repository summary (tree + key files) with specific
    retrieved snippets to provide a comprehensive answer.

    Args:
        query: The user's natural language question.
        context: Relevant code snippets retrieved from the vector database.
        summary: The global repository compression layer (tree and key files).

    Returns:
        A markdown-formatted response from Gemini.
    """
    try:
        # Construct global context from the compression layer
        repo_context = f"File Tree:\n{summary.get('tree')}\n\nKey Files Content:\n"
        for path, content in summary.get('key_files', {}).items():
            repo_context += f"--- {path} ---\n{content}\n"

        full_prompt = (
            f"Global Repo Context:\n{repo_context}\n\n"
            f"Retrieved Snippets:\n{context}\n\n"
            f"User Question: {query}"
        )
        
        response = client.models.generate_content(
            model="gemini-3.1-flash-lite",
            config={
                "system_instruction": SYSTEM_PROMPT,
            },
            contents=full_prompt
        )
        
        if not response.text:
            logger.warning("Gemini returned an empty response.")
            return "I couldn't generate a response. Please try again."
            
        return response.text
        
    except Exception as e:
        logger.error(f"Gemini API call failed: {e}", exc_info=True)
        return "Sorry, I encountered an error while processing your request."
