import os
from typing import Any, Dict, Optional
from google import genai
from dotenv import load_dotenv
from utils.logger import logger

# Load environment variables (GEMINI_API_KEY)
load_dotenv(override=True)

api_key = os.getenv("GEMINI_API_KEY")
print(f"DEBUG: Using API Key starting with: {api_key[:10]}...")
if not api_key:
    logger.error("GEMINI_API_KEY not found in environment.")

client = genai.Client(api_key=api_key)

SYSTEM_PROMPT = """
You are Codebase Concierge, an expert software architect. 
You are part of a team:
- Analyst: Focuses on structure and dependencies.
- Retriever: Finds relevant code snippets.
- Explainer: Provides clear, architectural summaries and diagrams.

Use the provided code context to answer the user's question. 
Always reference file paths and line numbers.

DIAGRAM RULES:
- If the user asks for a diagram, flow, or architecture view, use Mermaid.js syntax.
- Wrap Mermaid code EXACTLY in ```mermaid ... ``` blocks.
- Use 'graph TD' or 'sequenceDiagram' for most diagrams.
- Keep diagrams simple and readable.
- Ensure Mermaid syntax is valid (no special characters in node names unless quoted).
- If you generate a diagram, follow it with a brief textual explanation.

RESPONSE STYLE:
- Professional, technical, yet accessible.
- Use bold text for key components and file names.
- Focus on the "why" and "how" of the architecture, not just the "what".
"""

async def get_gemini_response_stream(query: str, context: str, summary: Dict[str, Any]):
    """Generates a streaming architectural explanation using Gemini 1.5 Flash.

    Yields:
        Chunks of text as they are generated by the model.
    """
    try:
        repo_context = f"File Tree:\n{summary.get('tree')}\n\nKey Files Content:\n"
        for path, content in summary.get('key_files', {}).items():
            repo_context += f"--- {path} ---\n{content}\n"

        full_prompt = (
            f"Global Repo Context:\n{repo_context}\n\n"
            f"Retrieved Snippets:\n{context}\n\n"
            f"User Question: {query}"
        )
        
        # Using stream_generate_content for lower TTFT (Time To First Token)
        response_stream = client.models.generate_content_stream(
            model="gemini-3.1-flash-lite",
            config={
                "system_instruction": SYSTEM_PROMPT,
            },
            contents=full_prompt
        )
        
        for chunk in response_stream:
            if chunk.text:
                yield chunk.text
                
    except Exception as e:
        logger.error(f"Gemini Streaming API call failed: {e}", exc_info=True)
        yield "Error: Encountered an issue while streaming the response."

def get_gemini_response(query: str, context: str, summary: Dict[str, Any]) -> str:
    """Generates a high-quality architectural explanation using Gemini 1.5 Flash.

    Combines the global repository summary (tree + key files) with specific
    retrieved snippets to provide a comprehensive answer.

    Args:
        query: The user's natural language question.
        context: Relevant code snippets retrieved from the vector database.
        summary: The global repository compression layer (tree and key files).

    Returns:
        A markdown-formatted response from Gemini.
    """
    try:
        # Construct global context from the compression layer
        repo_context = f"File Tree:\n{summary.get('tree')}\n\nKey Files Content:\n"
        for path, content in summary.get('key_files', {}).items():
            repo_context += f"--- {path} ---\n{content}\n"

        full_prompt = (
            f"Global Repo Context:\n{repo_context}\n\n"
            f"Retrieved Snippets:\n{context}\n\n"
            f"User Question: {query}"
        )
        
        response = client.models.generate_content(
            model="gemini-3.1-flash-lite",
            config={
                "system_instruction": SYSTEM_PROMPT,
            },
            contents=full_prompt
        )
        
        if not response.text:
            logger.warning("Gemini returned an empty response.")
            return "I couldn't generate a response. Please try again."
            
        return response.text
        
    except Exception as e:
        logger.error(f"Gemini API call failed: {e}", exc_info=True)
        return "Sorry, I encountered an error while processing your request."
